---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: llmaas-{{ .Values.username }}
  namespace: devworkspaces-{{ .Values.username }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace
spec:
  routingClass: che
  started: true
  contributions:
  - name: ide
    uri: {{ .Values.devworkspace.devfile }}
  template:
    projects:
    - name: llmaas-workspace
      git:
        remotes:
          origin: {{ .Values.devworkspace.projects.repoUrl }}
        checkoutFrom:
          revision: {{ .Values.devworkspace.projects.revision }}
    components:
    {{- toYaml .Values.devworkspace.components | nindent 4 }}
