---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: {{ .Values.devworkspace.name | default (printf "llmaas-%s" .Values.username) }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
  annotations:
    controller.devfile.io/devworkspace-creator: {{ .Values.username }}
    che.eclipse.org/devworkspace-creator: {{ .Values.username }}
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace
spec:
  routingClass: che
  started: true
  contributions:
  - name: ide
    uri: {{ .Values.devworkspace.devfile }}
  template:
    projects:
    - name: {{ .Values.devworkspace.name | default "llmaas-workspace" }}
      git:
        remotes:
          origin: {{ .Values.devworkspace.projects.repoUrl }}
        checkoutFrom:
          revision: {{ .Values.devworkspace.projects.revision }}
    components:
    {{- toYaml .Values.devworkspace.components | nindent 4 }}
